/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CompaniesIdRouteImport } from './routes/companies/$id'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences.index'
import { Route as ExperiencesNewRouteImport } from './routes/experiences.new'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesNewRouteImport } from './routes/resources.new'
import { Route as ExperiencesIdIndexRouteImport } from './routes/experiences.$id.index'
import { Route as ExperiencesIdEditRouteImport } from './routes/experiences.$id.edit'
import { Route as ResourcesIdEditRouteImport } from './routes/resources.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesNewRoute = ExperiencesNewRouteImport.update({
  id: '/experiences/new',
  path: '/experiences/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesNewRoute = ResourcesNewRouteImport.update({
  id: '/resources/new',
  path: '/resources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIdIndexRoute = ExperiencesIdIndexRouteImport.update({
  id: '/experiences/$id/',
  path: '/experiences/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIdEditRoute = ExperiencesIdEditRouteImport.update({
  id: '/experiences/$id/edit',
  path: '/experiences/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdEditRoute = ResourcesIdEditRouteImport.update({
  id: '/resources/$id/edit',
  path: '/resources/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/search': typeof SearchRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/experiences/$id/edit': typeof ExperiencesIdEditRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
  '/experiences/$id/': typeof ExperiencesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/search': typeof SearchRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/experiences/$id/edit': typeof ExperiencesIdEditRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
  '/experiences/$id': typeof ExperiencesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/search': typeof SearchRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/experiences/$id/edit': typeof ExperiencesIdEditRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
  '/experiences/$id/': typeof ExperiencesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/companies'
    | '/dashboard'
    | '/notes'
    | '/search'
    | '/companies/$id'
    | '/experiences/new'
    | '/resources/new'
    | '/experiences/'
    | '/resources/'
    | '/experiences/$id/edit'
    | '/resources/$id/edit'
    | '/experiences/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/companies'
    | '/dashboard'
    | '/notes'
    | '/search'
    | '/companies/$id'
    | '/experiences/new'
    | '/resources/new'
    | '/experiences'
    | '/resources'
    | '/experiences/$id/edit'
    | '/resources/$id/edit'
    | '/experiences/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/companies'
    | '/dashboard'
    | '/notes'
    | '/search'
    | '/companies/$id'
    | '/experiences/new'
    | '/resources/new'
    | '/experiences/'
    | '/resources/'
    | '/experiences/$id/edit'
    | '/resources/$id/edit'
    | '/experiences/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  NotesRoute: typeof NotesRoute
  SearchRoute: typeof SearchRoute
  ExperiencesNewRoute: typeof ExperiencesNewRoute
  ResourcesNewRoute: typeof ResourcesNewRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ExperiencesIdEditRoute: typeof ExperiencesIdEditRoute
  ResourcesIdEditRoute: typeof ResourcesIdEditRoute
  ExperiencesIdIndexRoute: typeof ExperiencesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/new': {
      id: '/experiences/new'
      path: '/experiences/new'
      fullPath: '/experiences/new'
      preLoaderRoute: typeof ExperiencesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/new': {
      id: '/resources/new'
      path: '/resources/new'
      fullPath: '/resources/new'
      preLoaderRoute: typeof ResourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$id/': {
      id: '/experiences/$id/'
      path: '/experiences/$id'
      fullPath: '/experiences/$id/'
      preLoaderRoute: typeof ExperiencesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$id/edit': {
      id: '/experiences/$id/edit'
      path: '/experiences/$id/edit'
      fullPath: '/experiences/$id/edit'
      preLoaderRoute: typeof ExperiencesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$id/edit': {
      id: '/resources/$id/edit'
      path: '/resources/$id/edit'
      fullPath: '/resources/$id/edit'
      preLoaderRoute: typeof ResourcesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  NotesRoute: NotesRoute,
  SearchRoute: SearchRoute,
  ExperiencesNewRoute: ExperiencesNewRoute,
  ResourcesNewRoute: ResourcesNewRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ExperiencesIdEditRoute: ExperiencesIdEditRoute,
  ResourcesIdEditRoute: ResourcesIdEditRoute,
  ExperiencesIdIndexRoute: ExperiencesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
