/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as CompaniesIdRouteImport } from './routes/companies/$id'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences.index'
import { Route as ExperiencesNewRouteImport } from './routes/experiences.new'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesNewRouteImport } from './routes/resources.new'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ExperiencesIdIndexRouteImport } from './routes/experiences.$id.index'
import { Route as ExperiencesIdEditRouteImport } from './routes/experiences.$id.edit'
import { Route as ResourcesIdEditRouteImport } from './routes/resources.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesNewRoute = ExperiencesNewRouteImport.update({
  id: '/experiences/new',
  path: '/experiences/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesNewRoute = ResourcesNewRouteImport.update({
  id: '/resources/new',
  path: '/resources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesIdIndexRoute = ExperiencesIdIndexRouteImport.update({
  id: '/experiences/$id/',
  path: '/experiences/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIdEditRoute = ExperiencesIdEditRouteImport.update({
  id: '/experiences/$id/edit',
  path: '/experiences/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdEditRoute = ResourcesIdEditRouteImport.update({
  id: '/resources/$id/edit',
  path: '/resources/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/experiences/$id/edit': typeof ExperiencesIdEditRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
  '/experiences/$id/': typeof ExperiencesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/experiences/$id/edit': typeof ExperiencesIdEditRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
  '/experiences/$id': typeof ExperiencesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/experiences/$id/edit': typeof ExperiencesIdEditRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
  '/experiences/$id/': typeof ExperiencesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/companies'
    | '/dashboard'
    | '/mcp'
    | '/notes'
    | '/reset-password'
    | '/search'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/companies/$id'
    | '/experiences/new'
    | '/resources/new'
    | '/experiences/'
    | '/resources/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/experiences/$id/edit'
    | '/resources/$id/edit'
    | '/experiences/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/companies'
    | '/dashboard'
    | '/mcp'
    | '/notes'
    | '/reset-password'
    | '/search'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/companies/$id'
    | '/experiences/new'
    | '/resources/new'
    | '/experiences'
    | '/resources'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/experiences/$id/edit'
    | '/resources/$id/edit'
    | '/experiences/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/companies'
    | '/dashboard'
    | '/mcp'
    | '/notes'
    | '/reset-password'
    | '/search'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/companies/$id'
    | '/experiences/new'
    | '/resources/new'
    | '/experiences/'
    | '/resources/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/experiences/$id/edit'
    | '/resources/$id/edit'
    | '/experiences/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  McpRoute: typeof McpRoute
  NotesRoute: typeof NotesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ExperiencesNewRoute: typeof ExperiencesNewRoute
  ResourcesNewRoute: typeof ResourcesNewRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ExperiencesIdEditRoute: typeof ExperiencesIdEditRoute
  ResourcesIdEditRoute: typeof ResourcesIdEditRoute
  ExperiencesIdIndexRoute: typeof ExperiencesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/new': {
      id: '/experiences/new'
      path: '/experiences/new'
      fullPath: '/experiences/new'
      preLoaderRoute: typeof ExperiencesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/new': {
      id: '/resources/new'
      path: '/resources/new'
      fullPath: '/resources/new'
      preLoaderRoute: typeof ResourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$id/': {
      id: '/experiences/$id/'
      path: '/experiences/$id'
      fullPath: '/experiences/$id/'
      preLoaderRoute: typeof ExperiencesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$id/edit': {
      id: '/experiences/$id/edit'
      path: '/experiences/$id/edit'
      fullPath: '/experiences/$id/edit'
      preLoaderRoute: typeof ExperiencesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$id/edit': {
      id: '/resources/$id/edit'
      path: '/resources/$id/edit'
      fullPath: '/resources/$id/edit'
      preLoaderRoute: typeof ResourcesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  McpRoute: McpRoute,
  NotesRoute: NotesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ExperiencesNewRoute: ExperiencesNewRoute,
  ResourcesNewRoute: ResourcesNewRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ExperiencesIdEditRoute: ExperiencesIdEditRoute,
  ResourcesIdEditRoute: ResourcesIdEditRoute,
  ExperiencesIdIndexRoute: ExperiencesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
